export interface Field {
  name: string,
  type: string,
  scale: number,
  offset: number
}

export const FIELDS: { [index: string]: { [index: string]: Field }} = {
  "0": {
    "0": {
      "name": "filetype",
      "type": "enumFile",
      "scale": 0,
      "offset": 0,
    },
    "1": {
      "name": "manufacturer",
      "type": "enumManufacturer",
      "scale": 0,
      "offset": 0,
    },
    "2": {
      "name": "garminProduct",
      "type": "raw",
      "scale": 0,
      "offset": 0,
    },
    "3": {
      "name": "serialNumber",
      "type": "raw",
      "scale": 0,
      "offset": 0,
    },
    "4": {
      "name": "timeCreated",
      "type": "dateTime",
      "scale": 0,
      "offset": 0,
    },
    "5": {
      "name": "number",
      "type": "raw",
      "scale": 0,
      "offset": 0,
    },
    "8": {
      "name": "productName",
      "type": "raw",
      "scale": 0,
      "offset": 0,
    },
  },
  "2": {
    "0": {
      "name": "activityTimeZone",
      "type": "unit8",
      "scale": 0,
      "offset": 0,
    },
    "1": {
      "name": "utcOffset",
      "type": "unit32",
      "scale": 0,
      "offset": 0,
    },
    "2": {
      "name": "timeOffset",
      "type": "unit32",
      "scale": 0,
      "offset": 0,
    },
    "4": {
      "name": "timeMode",
      "type": "enumTimeMode",
      "scale": 0,
      "offset": 0,
    },
    "5": {
      "name": "timeZoneOffset",
      "type": "sint8",
      "scale": 4,
      "offset": 0,
    },
    "36": {
      "name": "backlightMode",
      "type": "enumBacklightMode",
      "scale": 0,
      "offset": 0,
    },
    "39": {
      "name": "clockTime",
      "type": "dateTime",
      "scale": 0,
      "offset": 0,
    },
    "40": {
      "name": "pagesEnabled",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "46": {
      "name": "moveAlertEnabled",
      "type": "bool",
      "scale": 0,
      "offset": 0,
    },
    "47": {
      "name": "dateMode",
      "type": "enumDateMode",
      "scale": 0,
      "offset": 0,
    },
    "55": {
      "name": "displayOrientation",
      "type": "enumDisplayOrientation",
      "scale": 0,
      "offset": 0,
    },
    "56": {
      "name": "mountingSide",
      "type": "enumSide",
      "scale": 0,
      "offset": 0,
    },
    "57": {
      "name": "defaultPage",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "58": {
      "name": "autosyncMinSteps",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "59": {
      "name": "autoSyncMinTime",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "80": {
      "name": "lactateThresholdAutodetectEnabled",
      "type": "bool",
      "scale": 0,
      "offset": 0,
    },
    "86": {
      "name": "bleAutoUploadEnabled",
      "type": "bool",
      "scale": 0,
      "offset": 0,
    },
    "89": {
      "name": "autoSyncFrequency",
      "type": "enumAutoSyncFrequency",
      "scale": 0,
      "offset": 0,
    },
    "90": {
      "name": "autoActivityDetect",
      "type": "uint32",
      "scale": 0,
      "offset": 0,
    },
    "94": {
      "name": "numberOfScreens",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "95": {
      "name": "smartNotificationDisplayOrientation",
      "type": "enumDisplayOrientation",
      "scale": 0,
      "offset": 0,
    },
    "134": {
      "name": "tapInterface",
      "type": "enumSwitch",
      "scale": 0,
      "offset": 0,
    },
  },
  "3": {
    "254": {
      "name": "messageIndex",
      "type": "messageIndex",
      "scale": 0,
      "offset": 0,
    },
    "0": {
      "name": "friendlyName",
      "type": "string",
      "scale": 0,
      "offset": 0,
    },
    "1": {
      "name": "gender",
      "type": "enumGender",
      "scale": 0,
      "offset": 0,
    },
    "2": {
      "name": "age",
      "type": "raw",
      "scale": 0,
      "offset": 0,
    },
    "3": {
      "name": "height",
      "type": "uint8",
      "scale": 100,
      "offset": 0,
    },
    "4": {
      "name": "weight",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "5": {
      "name": "language",
      "type": "enumLanguage",
      "scale": 0,
      "offset": 0,
    },
    "6": {
      "name": "elevSetting",
      "type": "enumDisplayMeasure",
      "scale": 0,
      "offset": 0,
    },
    "7": {
      "name": "weightSetting",
      "type": "enumDisplayMeasure",
      "scale": 0,
      "offset": 0,
    },
    "8": {
      "name": "restingHeartRate",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "9": {
      "name": "defaultMaxRunningHeartRate",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "10": {
      "name": "defaultMaxBikingHeartRate",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "11": {
      "name": "defaultMaxHeartRate",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "12": {
      "name": "hrSetting",
      "type": "enumDisplayHeart",
      "scale": 0,
      "offset": 0,
    },
    "13": {
      "name": "speedSetting",
      "type": "enumDisplayMeasure",
      "scale": 0,
      "offset": 0,
    },
    "14": {
      "name": "distSetting",
      "type": "enumDisplayMeasure",
      "scale": 0,
      "offset": 0,
    },
    "16": {
      "name": "powerSetting",
      "type": "enumDisplayPower",
      "scale": 0,
      "offset": 0,
    },
    "17": {
      "name": "activityClass",
      "type": "enumActivityClass",
      "scale": 0,
      "offset": 0,
    },
    "18": {
      "name": "positionSetting",
      "type": "enumDisplayPosition",
      "scale": 0,
      "offset": 0,
    },
    "21": {
      "name": "temperatureSetting",
      "type": "enumDisplayMeasure",
      "scale": 0,
      "offset": 0,
    },
    "22": {
      "name": "localId",
      "type": "userLocalId",
      "scale": 0,
      "offset": 0,
    },
    "23": {
      "name": "globalId",
      "type": "byte",
      "scale": 0,
      "offset": 0,
    },
    "30": {
      "name": "heightSetting",
      "type": "enumDisplayMeasure",
      "scale": 0,
      "offset": 0,
    },
  },
  "6": {
    "254": {
      "name": "messageIndex",
      "type": "messageIndex",
      "scale": 0,
      "offset": 0,
    },
    "0": {
      "name": "name",
      "type": "string",
      "scale": 0,
      "offset": 0,
    },
    "1": {
      "name": "sport",
      "type": "enumSport",
      "scale": 0,
      "offset": 0,
    },
    "2": {
      "name": "subSport",
      "type": "enumSubSport",
      "scale": 0,
      "offset": 0,
    },
    "3": {
      "name": "odometer",
      "type": "uint32",
      "scale": 100,
      "offset": 0,
    },
    "4": {
      "name": "bikeSpdAntId",
      "type": "uint16z",
      "scale": 0,
      "offset": 0,
    },
    "5": {
      "name": "bikeCadAntId",
      "type": "uint16z",
      "scale": 0,
      "offset": 0,
    },
    "6": {
      "name": "bikeSpdcadAntId",
      "type": "uint16z",
      "scale": 0,
      "offset": 0,
    },
    "7": {
      "name": "bikePowerAntId",
      "type": "uint16z",
      "scale": 0,
      "offset": 0,
    },
    "8": {
      "name": "customWheelsize",
      "type": "uint16",
      "scale": 1000,
      "offset": 0,
    },
    "9": {
      "name": "autoWheelsize",
      "type": "uint16",
      "scale": 1000,
      "offset": 0,
    },
    "10": {
      "name": "bikeWeight",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "11": {
      "name": "powerCalFactor",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "12": {
      "name": "autoWheelCal",
      "type": "bool",
      "scale": 0,
      "offset": 0,
    },
    "13": {
      "name": "autoPowerZero",
      "type": "bool",
      "scale": 0,
      "offset": 0,
    },
    "14": {
      "name": "id",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "15": {
      "name": "spdEnabled",
      "type": "bool",
      "scale": 0,
      "offset": 0,
    },
    "16": {
      "name": "cadEnabled",
      "type": "bool",
      "scale": 0,
      "offset": 0,
    },
    "17": {
      "name": "spdcadEnabled",
      "type": "bool",
      "scale": 0,
      "offset": 0,
    },
    "18": {
      "name": "powerEnabled",
      "type": "bool",
      "scale": 0,
      "offset": 0,
    },
    "19": {
      "name": "crankLength",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "20": {
      "name": "enabled",
      "type": "bool",
      "scale": 0,
      "offset": 0,
    },
    "21": {
      "name": "bikeSpdAntIdTransType",
      "type": "uint8z",
      "scale": 0,
      "offset": 0,
    },
    "22": {
      "name": "bikeCadAntIdTransType",
      "type": "uint8z",
      "scale": 0,
      "offset": 0,
    },
    "23": {
      "name": "bikeSpdcadAntIdTransType",
      "type": "uint8z",
      "scale": 0,
      "offset": 0,
    },
    "24": {
      "name": "bikePowerAntIdTransType",
      "type": "uint8z",
      "scale": 0,
      "offset": 0,
    },
  },
  "7": {
    "1": {
      "name": "maxHeartRate",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "2": {
      "name": "thresholdHeartRate",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "3": {
      "name": "functionalThresholdPower",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "5": {
      "name": "hrCalcType",
      "type": "hrZoneCalc",
      "scale": 0,
      "offset": 0,
    },
    "7": {
      "name": "pwrCalcType",
      "type": "pwrZoneCalc",
      "scale": 0,
      "offset": 0,
    },
  },
  "18": {
    "254": {
      "name": "messageIndex",
      "type": "messageIndex",
      "scale": 0,
      "offset": 0,
    },
    "253": {
      "name": "timestamp",
      "type": "dateTime",
      "scale": 0,
      "offset": 0,
    },
    "0": {
      "name": "event",
      "type": "enumEvent",
      "scale": 0,
      "offset": 0,
    },
    "1": {
      "name": "eventType",
      "type": "enumEventType",
      "scale": 0,
      "offset": 0,
    },
    "2": {
      "name": "startTime",
      "type": "dateTime",
      "scale": 0,
      "offset": 0,
    },
    "3": {
      "name": "startPositionLat",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "4": {
      "name": "startPositionLong",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "5": {
      "name": "sport",
      "type": "enumSport",
      "scale": 0,
      "offset": 0,
    },
    "6": {
      "name": "subSport",
      "type": "enumSubSport",
      "scale": 0,
      "offset": 0,
    },
    "7": {
      "name": "totalElapsedTime",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "8": {
      "name": "totalTimerTime",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "9": {
      "name": "totalDistance",
      "type": "uint32",
      "scale": 100,
      "offset": 0,
    },
    "10": {
      "name": "totalCycles",
      "type": "uint32",
      "scale": 0,
      "offset": 0,
    },
    "11": {
      "name": "totalCalories",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "13": {
      "name": "totalFatCalories",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "14": {
      "name": "avgSpeed",
      "type": "uint16",
      "scale": 1000,
      "offset": 0,
    },
    "15": {
      "name": "maxSpeed",
      "type": "uint16",
      "scale": 1000,
      "offset": 0,
    },
    "16": {
      "name": "avgHeartRate",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "17": {
      "name": "maxHeartRate",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "18": {
      "name": "avgCadence",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "19": {
      "name": "maxCadence",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "20": {
      "name": "avgPower",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "21": {
      "name": "maxPower",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "22": {
      "name": "totalAscent",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "23": {
      "name": "totalDescent",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "24": {
      "name": "totalTrainingEffect",
      "type": "uint8",
      "scale": 10,
      "offset": 0,
    },
    "25": {
      "name": "firstLapIndex",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "26": {
      "name": "numLaps",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "27": {
      "name": "eventGroup",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "28": {
      "name": "trigger",
      "type": "enumSessionTrigger",
      "scale": 0,
      "offset": 0,
    },
    "29": {
      "name": "necLat",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "30": {
      "name": "necLong",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "31": {
      "name": "swcLat",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "32": {
      "name": "swcLong",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "34": {
      "name": "normalizedPower",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "35": {
      "name": "trainingStressScore",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "36": {
      "name": "intensityFactor",
      "type": "uint16",
      "scale": 1000,
      "offset": 0,
    },
    "37": {
      "name": "leftRightBalance",
      "type": "leftRightBalance100",
      "scale": 0,
      "offset": 0,
    },
    "41": {
      "name": "avgStrokeCount",
      "type": "uint32",
      "scale": 10,
      "offset": 0,
    },
    "42": {
      "name": "avgStrokeDistance",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "44": {
      "name": "poolLength",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "45": {
      "name": "thresholdPower",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "46": {
      "name": "poolLengthUnit",
      "type": "enumDisplayMeasure",
      "scale": 0,
      "offset": 0,
    },
    "47": {
      "name": "numActiveLengths",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "48": {
      "name": "totalWork",
      "type": "uint32",
      "scale": 0,
      "offset": 0,
    },
    "49": {
      "name": "avgAltitude",
      "type": "uint16",
      "scale": 5,
      "offset": 0,
    },
    "50": {
      "name": "maxAltitude",
      "type": "uint16",
      "scale": 5,
      "offset": 0,
    },
    "51": {
      "name": "gpsAccuracy",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "52": {
      "name": "avgGrade",
      "type": "sint16",
      "scale": 100,
      "offset": 0,
    },
    "53": {
      "name": "avgPosGrade",
      "type": "sint16",
      "scale": 100,
      "offset": 0,
    },
    "54": {
      "name": "avgNegGrade",
      "type": "sint16",
      "scale": 100,
      "offset": 0,
    },
    "55": {
      "name": "maxPosGrade",
      "type": "sint16",
      "scale": 100,
      "offset": 0,
    },
    "56": {
      "name": "maxNegGrade",
      "type": "sint16",
      "scale": 100,
      "offset": 0,
    },
    "57": {
      "name": "avgTemperature",
      "type": "sint8",
      "scale": 0,
      "offset": 0,
    },
    "58": {
      "name": "maxTemperature",
      "type": "sint8",
      "scale": 0,
      "offset": 0,
    },
    "59": {
      "name": "totalMovingTime",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "60": {
      "name": "avgPosVerticalSpeed",
      "type": "sint16",
      "scale": 1000,
      "offset": 0,
    },
    "61": {
      "name": "avgNegVerticalSpeed",
      "type": "sint16",
      "scale": 1000,
      "offset": 0,
    },
    "62": {
      "name": "maxPosVerticalSpeed",
      "type": "sint16",
      "scale": 1000,
      "offset": 0,
    },
    "63": {
      "name": "maxNegVerticalSpeed",
      "type": "sint16",
      "scale": 1000,
      "offset": 0,
    },
    "64": {
      "name": "minHeartRate",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "65": {
      "name": "timeInHrZone",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "66": {
      "name": "timeInSpeedZone",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "67": {
      "name": "timeInCadenceZone",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "68": {
      "name": "timeInPowerZone",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "69": {
      "name": "avgLapTime",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "70": {
      "name": "bestLapIndex",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "71": {
      "name": "minAltitude",
      "type": "uint16",
      "scale": 5,
      "offset": 500,
    },
    "82": {
      "name": "playerScore",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "83": {
      "name": "opponentScore",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "84": {
      "name": "opponentName",
      "type": "string",
      "scale": 0,
      "offset": 0,
    },
    "85": {
      "name": "strokeCount",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "86": {
      "name": "zoneCount",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "87": {
      "name": "maxBallSpeed",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "88": {
      "name": "avgBallSpeed",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "89": {
      "name": "avgVerticalOscillation",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "90": {
      "name": "avgStanceTimePercent",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "91": {
      "name": "avgStanceTime",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "92": {
      "name": "avgFractionalCadence",
      "type": "uint8",
      "scale": 128,
      "offset": 0,
    },
    "93": {
      "name": "maxFractionalCadence",
      "type": "uint8",
      "scale": 128,
      "offset": 0,
    },
    "94": {
      "name": "totalFractionalCycles",
      "type": "uint8",
      "scale": 128,
      "offset": 0,
    },
    "95": {
      "name": "avgTotalHemoglobinConc",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "96": {
      "name": "minTotalHemoglobinConc",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "97": {
      "name": "maxTotalHemoglobinConc",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "98": {
      "name": "avgSaturatedHemoglobinPercent",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "99": {
      "name": "minSaturatedHemoglobinPercent",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "100": {
      "name": "maxSaturatedHemoglobinPercent",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "101": {
      "name": "avgLeftTorqueEffectiveness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "102": {
      "name": "avgRightTorqueEffectiveness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "103": {
      "name": "avgLeftPedalSmoothness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "104": {
      "name": "avgRightPedalSmoothness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "105": {
      "name": "avgCombinedPedalSmoothness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "107": {
      "name": "numFrontGearChanges",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "108": {
      "name": "numRearGearChanges",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "111": {
      "name": "sportIndex",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "112": {
      "name": "timeStanding",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "113": {
      "name": "standCount",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "114": {
      "name": "avgLeftPco",
      "type": "sint8",
      "scale": 0,
      "offset": 0,
    },
    "115": {
      "name": "avgRightPco",
      "type": "sint8",
      "scale": 0,
      "offset": 0,
    },
    "116": {
      "name": "avgLeftPowerPhase",
      "type": "uint8",
      "scale": 0.7111111,
      "offset": 0,
    },
    "117": {
      "name": "avgLeftPowerPhasePeak",
      "type": "uint8",
      "scale": 0.7111111,
      "offset": 0,
    },
    "118": {
      "name": "avgRightPowerPhase",
      "type": "uint8",
      "scale": 0.7111111,
      "offset": 0,
    },
    "119": {
      "name": "avgRightPowerPhasePeak",
      "type": "uint8",
      "scale": 0.7111111,
      "offset": 0,
    },
    "120": {
      "name": "avgPowerPosition",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "121": {
      "name": "maxPowerPosition",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "122": {
      "name": "avgCadencePosition",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "123": {
      "name": "maxCadencePosition",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "124": {
      "name": "enhancedAvgSpeed",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "125": {
      "name": "enhancedMaxSpeed",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "126": {
      "name": "enhancedAvgAltitude",
      "type": "uint32",
      "scale": 5,
      "offset": 500,
    },
    "127": {
      "name": "enhancedMinAltitude",
      "type": "uint32",
      "scale": 5,
      "offset": 500,
    },
    "128": {
      "name": "enhancedMaxAltitude",
      "type": "uint32",
      "scale": 5,
      "offset": 500,
    },
    "129": {
      "name": "avgLevMotorPower",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "130": {
      "name": "maxLevMotorPower",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "131": {
      "name": "levBatteryConsumption",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
  },
  "19": {
    "254": {
      "name": "messageIndex",
      "type": "messageIndex",
      "scale": 0,
      "offset": 0,
    },
    "253": {
      "name": "timestamp",
      "type": "dateTime",
      "scale": 0,
      "offset": 0,
    },
    "0": {
      "name": "event",
      "type": "enumEvent",
      "scale": 0,
      "offset": 0,
    },
    "1": {
      "name": "eventType",
      "type": "enumEventType",
      "scale": 0,
      "offset": 0,
    },
    "2": {
      "name": "startTime",
      "type": "dateTime",
      "scale": 0,
      "offset": 0,
    },
    "3": {
      "name": "startPositionLat",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "4": {
      "name": "startPositionLong",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "5": {
      "name": "endPositionLat",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "6": {
      "name": "endPositionLong",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "7": {
      "name": "totalElapsedTime",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "8": {
      "name": "totalTimerTime",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "9": {
      "name": "totalDistance",
      "type": "uint32",
      "scale": 100,
      "offset": 0,
    },
    "10": {
      "name": "totalCycles",
      "type": "uint32",
      "scale": 0,
      "offset": 0,
    },
    "11": {
      "name": "totalCalories",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "12": {
      "name": "totalFatCalories",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "13": {
      "name": "avgSpeed",
      "type": "uint16",
      "scale": 1000,
      "offset": 0,
    },
    "14": {
      "name": "maxSpeed",
      "type": "uint16",
      "scale": 1000,
      "offset": 0,
    },
    "15": {
      "name": "avgHeartRate",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "16": {
      "name": "maxHeartRate",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "17": {
      "name": "avgCadence",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "18": {
      "name": "maxCadence",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "19": {
      "name": "avgPower",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "20": {
      "name": "maxPower",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "21": {
      "name": "totalAscent",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "22": {
      "name": "totalDescent",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "23": {
      "name": "intensity",
      "type": "enumIntensity",
      "scale": 0,
      "offset": 0,
    },
    "24": {
      "name": "lapTrigger",
      "type": "enumLapTrigger",
      "scale": 0,
      "offset": 0,
    },
    "25": {
      "name": "sport",
      "type": "enumSport",
      "scale": 0,
      "offset": 0,
    },
    "26": {
      "name": "eventGroup",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "27": {
      "name": "necLat",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "28": {
      "name": "necLong",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "29": {
      "name": "swcLat",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "30": {
      "name": "swcLong",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "32": {
      "name": "numLengths",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "33": {
      "name": "normalizedPower",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "34": {
      "name": "leftRightBalance",
      "type": "leftRightBalance100",
      "scale": 0,
      "offset": 0,
    },
    "35": {
      "name": "firstLengthIndex",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "37": {
      "name": "avgStrokeDistance",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "38": {
      "name": "swimStroke",
      "type": "enumSwimStroke",
      "scale": 0,
      "offset": 0,
    },
    "39": {
      "name": "subSport",
      "type": "enumSubSport",
      "scale": 0,
      "offset": 0,
    },
    "40": {
      "name": "numActiveLengths",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "41": {
      "name": "totalWork",
      "type": "uint32",
      "scale": 0,
      "offset": 0,
    },
    "42": {
      "name": "avgAltitude",
      "type": "uint16",
      "scale": 5,
      "offset": 500,
    },
    "43": {
      "name": "maxAltitude",
      "type": "uint16",
      "scale": 5,
      "offset": 500,
    },
    "44": {
      "name": "gpsAccuracy",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "45": {
      "name": "avgGrade",
      "type": "sint16",
      "scale": 100,
      "offset": 0,
    },
    "46": {
      "name": "avgPosGrade",
      "type": "sint16",
      "scale": 100,
      "offset": 0,
    },
    "47": {
      "name": "avgNegGrade",
      "type": "sint16",
      "scale": 100,
      "offset": 0,
    },
    "48": {
      "name": "maxPosGrade",
      "type": "sint16",
      "scale": 100,
      "offset": 0,
    },
    "49": {
      "name": "maxNegGrade",
      "type": "sint16",
      "scale": 100,
      "offset": 0,
    },
    "50": {
      "name": "avgTemperature",
      "type": "sint8",
      "scale": 0,
      "offset": 0,
    },
    "51": {
      "name": "maxTemperature",
      "type": "sint8",
      "scale": 0,
      "offset": 0,
    },
    "52": {
      "name": "totalMovingTime",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "53": {
      "name": "avgPosVerticalSpeed",
      "type": "sint16",
      "scale": 1000,
      "offset": 0,
    },
    "54": {
      "name": "avgNegVerticalSpeed",
      "type": "sint16",
      "scale": 1000,
      "offset": 0,
    },
    "55": {
      "name": "maxPosVerticalSpeed",
      "type": "sint16",
      "scale": 1000,
      "offset": 0,
    },
    "56": {
      "name": "maxNegVerticalSpeed",
      "type": "sint16",
      "scale": 1000,
      "offset": 0,
    },
    "57": {
      "name": "timeInHrZone",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "58": {
      "name": "timeInSpeedZone",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "59": {
      "name": "timeInCadenceZone",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "60": {
      "name": "timeInPowerZone",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "61": {
      "name": "repetitionNum",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "62": {
      "name": "minAltitude",
      "type": "uint16",
      "scale": 5,
      "offset": 500,
    },
    "63": {
      "name": "minHeartRate",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "71": {
      "name": "wktStepIndex",
      "type": "messageIndex",
      "scale": 0,
      "offset": 0,
    },
    "74": {
      "name": "opponentScore",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "75": {
      "name": "strokeCount",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "76": {
      "name": "zoneCount",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "77": {
      "name": "avgVerticalOscillation",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "78": {
      "name": "avgStanceTimePercent",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "79": {
      "name": "avgStanceTime",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "80": {
      "name": "avgFractionalCadence",
      "type": "uint8",
      "scale": 128,
      "offset": 0,
    },
    "81": {
      "name": "maxFractionalCadence",
      "type": "uint8",
      "scale": 128,
      "offset": 0,
    },
    "82": {
      "name": "totalFractionalCycles",
      "type": "uint8",
      "scale": 128,
      "offset": 0,
    },
    "83": {
      "name": "playerScore",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "84": {
      "name": "avgTotalHemoglobinConc",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "85": {
      "name": "minTotalHemoglobinConc",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "86": {
      "name": "maxTotalHemoglobinConc",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "87": {
      "name": "avgSaturatedHemoglobinPercent",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "88": {
      "name": "minSaturatedHemoglobinPercent",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "89": {
      "name": "maxSaturatedHemoglobinPercent",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "91": {
      "name": "avgLeftTorqueEffectiveness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "92": {
      "name": "avgRightTorqueEffectiveness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "93": {
      "name": "avgLeftPedalSmoothness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "94": {
      "name": "avgRightPedalSmoothness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "95": {
      "name": "avgCombinedPedalSmoothness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "96": {
      "name": "numFrontGearChanges",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "97": {
      "name": "numRearGearChanges",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "98": {
      "name": "timeStanding",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "99": {
      "name": "standCount",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "100": {
      "name": "avgLeftPco",
      "type": "sint8",
      "scale": 0,
      "offset": 0,
    },
    "101": {
      "name": "avgRightPco",
      "type": "sint8",
      "scale": 0,
      "offset": 0,
    },
    "102": {
      "name": "avgLeftPowerPhase",
      "type": "uint8",
      "scale": 0.7111111,
      "offset": 0,
    },
    "103": {
      "name": "avgLeftPowerPhasePeak",
      "type": "uint8",
      "scale": 0.7111111,
      "offset": 0,
    },
    "104": {
      "name": "avgRightPowerPhase",
      "type": "uint8",
      "scale": 0.7111111,
      "offset": 0,
    },
    "105": {
      "name": "avgRightPowerPhasePeak",
      "type": "uint8",
      "scale": 0.7111111,
      "offset": 0,
    },
    "106": {
      "name": "avgPowerPosition",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "107": {
      "name": "maxPowerPosition",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "108": {
      "name": "avgCadencePosition",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "109": {
      "name": "maxCadencePosition",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "110": {
      "name": "enhancedAvgSpeed",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "111": {
      "name": "enhancedMaxSpeed",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "112": {
      "name": "enhancedAvgAltitude",
      "type": "uint32",
      "scale": 5,
      "offset": 500,
    },
    "113": {
      "name": "enhancedMinAltitude",
      "type": "uint32",
      "scale": 5,
      "offset": 500,
    },
    "114": {
      "name": "enhancedMaxAltitude",
      "type": "uint32",
      "scale": 5,
      "offset": 500,
    },
    "115": {
      "name": "avgLevMotorPower",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "116": {
      "name": "maxLevMotorPower",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "117": {
      "name": "levBatteryConsumption",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
  },
  "20": {
    "253": {
      "name": "timestamp",
      "type": "dateTime",
      "scale": 0,
      "offset": 0,
    },
    "0": {
      "name": "positionLat",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "1": {
      "name": "positionLong",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "2": {
      "name": "altitude",
      "type": "uint16",
      "scale": 5,
      "offset": 500,
    },
    "3": {
      "name": "heartRate",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "4": {
      "name": "cadence",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "5": {
      "name": "distance",
      "type": "uint32",
      "scale": 100,
      "offset": 0,
    },
    "6": {
      "name": "speed",
      "type": "uint16",
      "scale": 1000,
      "offset": 0,
    },
    "7": {
      "name": "power",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "8": {
      "name": "compressedSpeedDistance",
      "type": "byte",
      "scale": 100,
      "offset": 0,
    },
    "9": {
      "name": "grade",
      "type": "sint16",
      "scale": 100,
      "offset": 0,
    },
    "10": {
      "name": "resistance",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "11": {
      "name": "timeFromCourse",
      "type": "sint32",
      "scale": 1000,
      "offset": 0,
    },
    "12": {
      "name": "cycleLength",
      "type": "uint8",
      "scale": 100,
      "offset": 0,
    },
    "13": {
      "name": "temperature",
      "type": "sint8",
      "scale": 0,
      "offset": 0,
    },
    "17": {
      "name": "speed1s",
      "type": "uint8",
      "scale": 16,
      "offset": 0,
    },
    "18": {
      "name": "cycles",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "19": {
      "name": "totalCycles",
      "type": "uint32",
      "scale": 0,
      "offset": 0,
    },
    "28": {
      "name": "compressedAccumulatedPower",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "29": {
      "name": "accumulatedPower",
      "type": "uint32",
      "scale": 0,
      "offset": 0,
    },
    "30": {
      "name": "leftRightBalance",
      "type": "leftRightBalance",
      "scale": 0,
      "offset": 0,
    },
    "31": {
      "name": "gpsAccuracy",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "32": {
      "name": "verticalSpeed",
      "type": "sint16",
      "scale": 1000,
      "offset": 0,
    },
    "33": {
      "name": "calories",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "39": {
      "name": "verticalOscillation",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "40": {
      "name": "stanceTimePercent",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "41": {
      "name": "stanceTime",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "42": {
      "name": "activityType",
      "type": "activityType",
      "scale": 0,
      "offset": 0,
    },
    "43": {
      "name": "leftTorqueEffectiveness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "44": {
      "name": "rightTorqueEffectiveness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "45": {
      "name": "leftPedalSmoothness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "46": {
      "name": "rightPedalSmoothness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "47": {
      "name": "combinedPedalSmoothness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "48": {
      "name": "time128",
      "type": "uint8",
      "scale": 128,
      "offset": 0,
    },
    "49": {
      "name": "strokeType",
      "type": "strokeType",
      "scale": 0,
      "offset": 0,
    },
    "50": {
      "name": "zone",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "51": {
      "name": "ballSpeed",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "52": {
      "name": "cadence256",
      "type": "uint16",
      "scale": 256,
      "offset": 0,
    },
    "53": {
      "name": "fractionalCadence",
      "type": "uint8",
      "scale": 128,
      "offset": 0,
    },
    "54": {
      "name": "totalHemoglobinConc",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "55": {
      "name": "totalHemoglobinConcMin",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "56": {
      "name": "totalHemoglobinConcMax",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "57": {
      "name": "saturatedHemoglobinPercent",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "58": {
      "name": "saturatedHemoglobinPercentMin",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "59": {
      "name": "saturatedHemoglobinPercentMax",
      "type": "uint16",
      "scale": 10,
      "offset": 0,
    },
    "62": {
      "name": "deviceIndex",
      "type": "deviceIndex",
      "scale": 0,
      "offset": 0,
    },
    "67": {
      "name": "leftPco",
      "type": "sint8",
      "scale": 0,
      "offset": 0,
    },
    "68": {
      "name": "rightPco",
      "type": "sint8",
      "scale": 0,
      "offset": 0,
    },
    "69": {
      "name": "leftPowerPhase",
      "type": "uint8",
      "scale": 0.7111111,
      "offset": 0,
    },
    "70": {
      "name": "leftPowerPhasePeak",
      "type": "uint8",
      "scale": 0.7111111,
      "offset": 0,
    },
    "71": {
      "name": "rightPowerPhase",
      "type": "uint8",
      "scale": 0.7111111,
      "offset": 0,
    },
    "72": {
      "name": "rightPowerPhasePeak",
      "type": "uint8",
      "scale": 0.7111111,
      "offset": 0,
    },
    "73": {
      "name": "enhancedSpeed",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "78": {
      "name": "enhancedAltitude",
      "type": "uint32",
      "scale": 5,
      "offset": 500,
    },
    "81": {
      "name": "batterySoc",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "82": {
      "name": "motorPower",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
  },
  "21": {
    "253": {
      "name": "timestamp",
      "type": "dateTime",
      "scale": 0,
      "offset": 0,
    },
    "0": {
      "name": "event",
      "type": "enumEvent",
      "scale": 0,
      "offset": 0,
    },
    "1": {
      "name": "eventType",
      "type": "enumEventType",
      "scale": 0,
      "offset": 0,
    },
    "2": {
      "name": "data16",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "3": {
      "name": "data",
      "type": "uint32",
      "scale": 0,
      "offset": 0,
    },
    "4": {
      "name": "eventGroup",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "7": {
      "name": "score",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "8": {
      "name": "opponentScore",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "9": {
      "name": "frontGearNum",
      "type": "uint8z",
      "scale": 0,
      "offset": 0,
    },
    "10": {
      "name": "frontGear",
      "type": "uint8z",
      "scale": 0,
      "offset": 0,
    },
    "11": {
      "name": "rearGearNum",
      "type": "uint8z",
      "scale": 0,
      "offset": 0,
    },
    "12": {
      "name": "rearGear",
      "type": "uint8z",
      "scale": 0,
      "offset": 0,
    },
    "13": {
      "name": "deviceIndex",
      "type": "raw",
      "scale": 0,
      "offset": 0,
    },
  },
  "22": {
    "253": {
      "name": "timestamp",
      "type": "dateTime",
      "scale": 0,
      "offset": 0,
    },
    "0": {
      "name": "speed",
      "type": "deviceIndex",
      "scale": 0,
      "offset": 0,
    },
    "1": {
      "name": "distance",
      "type": "deviceIndex",
      "scale": 0,
      "offset": 0,
    },
    "2": {
      "name": "cadence",
      "type": "deviceIndex",
      "scale": 0,
      "offset": 0,
    },
    "3": {
      "name": "altitude",
      "type": "deviceIndex",
      "scale": 0,
      "offset": 0,
    },
    "4": {
      "name": "heart",
      "type": "deviceIndex",
      "scale": 0,
      "offset": 0,
    },
  },
  "23": {
    "253": {
      "name": "timestamp",
      "type": "dateTime",
      "scale": 0,
      "offset": 0,
    },
    "0": {
      "name": "deviceIndex",
      "type": "deviceIndex",
      "scale": 0,
      "offset": 0,
    },
    "1": {
      "name": "deviceType",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "2": {
      "name": "manufacturer",
      "type": "enumManufacturer",
      "scale": 0,
      "offset": 0,
    },
    "3": {
      "name": "serialNumber",
      "type": "uint32z",
      "scale": 0,
      "offset": 0,
    },
    "4": {
      "name": "product",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "5": {
      "name": "softwareVersion",
      "type": "uint16",
      "scale": 100,
      "offset": 0,
    },
    "6": {
      "name": "hardwareVersion",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "7": {
      "name": "cumOperatingTime",
      "type": "uint32",
      "scale": 0,
      "offset": 0,
    },
    "10": {
      "name": "batteryVoltage",
      "type": "uint16",
      "scale": 256,
      "offset": 0,
    },
    "11": {
      "name": "batteryStatus",
      "type": "enumBatteryStatus",
      "scale": 0,
      "offset": 0,
    },
    "18": {
      "name": "sensorPosition",
      "type": "enumBodyLocation",
      "scale": 0,
      "offset": 0,
    },
    "19": {
      "name": "descriptor",
      "type": "string",
      "scale": 0,
      "offset": 0,
    },
    "20": {
      "name": "antTransmissionType",
      "type": "uint8z",
      "scale": 0,
      "offset": 0,
    },
    "21": {
      "name": "antDeviceNumber",
      "type": "uint16z",
      "scale": 0,
      "offset": 0,
    },
    "22": {
      "name": "antNetwork",
      "type": "enumAntNetwork",
      "scale": 0,
      "offset": 0,
    },
    "23": {
      "name": "serialNumber",
      "type": "raw",
      "scale": 0,
      "offset": 0,
    },
    "24": {
      "name": "sensorSerialNumber",
      "type": "raw",
      "scale": 0,
      "offset": 0,
    },
    "25": {
      "name": "sourceType",
      "type": "enumSourceType",
      "scale": 0,
      "offset": 0,
    },
    "27": {
      "name": "productName",
      "type": "string",
      "scale": 0,
      "offset": 0,
    },
  },
  "34": {
    "253": {
      "name": "timestamp",
      "type": "dateTime",
      "scale": 0,
      "offset": 0,
    },
    "0": {
      "name": "totalTimerTime",
      "type": "uint32",
      "scale": 0,
      "offset": 0,
    },
    "1": {
      "name": "numSessions",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "2": {
      "name": "type",
      "type": "enumActivity",
      "scale": 0,
      "offset": 0,
    },
    "3": {
      "name": "event",
      "type": "enumEvent",
      "scale": 0,
      "offset": 0,
    },
    "4": {
      "name": "eventType",
      "type": "enumEventType",
      "scale": 0,
      "offset": 0,
    },
    "5": {
      "name": "localTimestamp",
      "type": "localDateTime",
      "scale": 0,
      "offset": 0,
    },
    "6": {
      "name": "eventGroup",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
  },
  "49": {
    "0": {
      "name": "softwareVersion",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "1": {
      "name": "hardwareVersion",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
  },
  "72": {
    "253": {
      "name": "timestamp",
      "type": "dateTime",
      "scale": 0,
      "offset": 0,
    },
    "0": {
      "name": "type",
      "type": "enumFile",
      "scale": 0,
      "offset": 0,
    },
    "1": {
      "name": "manufacturer",
      "type": "enumManufacturer",
      "scale": 0,
      "offset": 0,
    },
    "2": {
      "name": "product",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "3": {
      "name": "serialNumber",
      "type": "uint32z",
      "scale": 0,
      "offset": 0,
    },
    "4": {
      "name": "timeCreated",
      "type": "dateTime",
      "scale": 0,
      "offset": 0,
    },
  },
  "101": {
    "254": {
      "name": "messageIndex",
      "type": "messageIndex",
      "scale": 0,
      "offset": 0,
    },
    "253": {
      "name": "timestamp",
      "type": "dateTime",
      "scale": 0,
      "offset": 0,
    },
    "0": {
      "name": "event",
      "type": "enumEvent",
      "scale": 0,
      "offset": 0,
    },
    "1": {
      "name": "eventType",
      "type": "enumEventType",
      "scale": 0,
      "offset": 0,
    },
    "2": {
      "name": "startTime",
      "type": "dateTime",
      "scale": 0,
      "offset": 0,
    },
    "3": {
      "name": "totalElapsedTime",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "4": {
      "name": "totalTimerTime",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "5": {
      "name": "totalStrokes",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "6": {
      "name": "avgSpeed",
      "type": "uint16",
      "scale": 1000,
      "offset": 0,
    },
    "7": {
      "name": "swimStroke",
      "type": "enumSwimStroke",
      "scale": 0,
      "offset": 0,
    },
    "9": {
      "name": "avgSwimmingCadence",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "10": {
      "name": "eventGroup",
      "type": "unit8",
      "scale": 0,
      "offset": 0,
    },
    "11": {
      "name": "totalCalories",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "12": {
      "name": "lengthType",
      "type": "enumLengthType",
      "scale": 0,
      "offset": 0,
    },
    "18": {
      "name": "playerScore",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "19": {
      "name": "opponentScore",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "20": {
      "name": "strokeCount",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "21": {
      "name": "zoneCount",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
  },
  "104": {
    "253": {
      "name": "timestamp",
      "type": "dateTime",
      "scale": 0,
      "offset": 0,
    },
    "0": {
      "name": "charge",
      "type": "raw",
      "scale": 0,
      "offset": 0,
    },
    "2": {
      "name": "percent",
      "type": "raw",
      "scale": 0,
      "offset": 0,
    },
  },
  "142": {
    "254": {
      "name": "messageIndex",
      "type": "messageIndex",
      "scale": 0,
      "offset": 0,
    },
    "253": {
      "name": "timestamp",
      "type": "dateTime",
      "scale": 0,
      "offset": 0,
    },
    "0": {
      "name": "event",
      "type": "event",
      "scale": 0,
      "offset": 0,
    },
    "1": {
      "name": "eventType",
      "type": "eventType",
      "scale": 0,
      "offset": 0,
    },
    "2": {
      "name": "startTime",
      "type": "dateTime",
      "scale": 0,
      "offset": 0,
    },
    "3": {
      "name": "startPositionLat",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "4": {
      "name": "startPositionLong",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "5": {
      "name": "endPositionLat",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "6": {
      "name": "endPositionLong",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "7": {
      "name": "totalElapsedTime",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "8": {
      "name": "totalTimerTime",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "9": {
      "name": "totalDistance",
      "type": "uint32",
      "scale": 100,
      "offset": 0,
    },
    "10": {
      "name": "totalCycles",
      "type": "uint32",
      "scale": 0,
      "offset": 0,
    },
    "11": {
      "name": "totalCalories",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "12": {
      "name": "totalFatCalories",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "13": {
      "name": "avgSpeed",
      "type": "uint16",
      "scale": 1000,
      "offset": 0,
    },
    "14": {
      "name": "maxSpeed",
      "type": "uint16",
      "scale": 1000,
      "offset": 0,
    },
    "15": {
      "name": "avgHeartRate",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "16": {
      "name": "maxHeartRate",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "17": {
      "name": "avgCadence",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "18": {
      "name": "maxCadence",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "19": {
      "name": "avgPower",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "20": {
      "name": "maxPower",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "21": {
      "name": "totalAscent",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "22": {
      "name": "totalDescent",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "23": {
      "name": "sport",
      "type": "sport",
      "scale": 0,
      "offset": 0,
    },
    "24": {
      "name": "eventGroup",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "25": {
      "name": "necLat",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "26": {
      "name": "necLong",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "27": {
      "name": "swcLat",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "28": {
      "name": "swcLong",
      "type": "coordinates",
      "scale": 0,
      "offset": 0,
    },
    "29": {
      "name": "name",
      "type": "string",
      "scale": 0,
      "offset": 0,
    },
    "30": {
      "name": "normalizedPower",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "31": {
      "name": "leftRightBalance",
      "type": "leftRightBalance100",
      "scale": 0,
      "offset": 0,
    },
    "32": {
      "name": "subSport",
      "type": "subSport",
      "scale": 0,
      "offset": 0,
    },
    "33": {
      "name": "totalWork",
      "type": "uint32",
      "scale": 0,
      "offset": 0,
    },
    "34": {
      "name": "avgAltitude",
      "type": "uint16",
      "scale": 5,
      "offset": 500,
    },
    "35": {
      "name": "maxAltitude",
      "type": "uint16",
      "scale": 5,
      "offset": 500,
    },
    "36": {
      "name": "gpsAccuracy",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "37": {
      "name": "avgGrade",
      "type": "sint16",
      "scale": 100,
      "offset": 0,
    },
    "38": {
      "name": "avgPosGrade",
      "type": "sint16",
      "scale": 100,
      "offset": 0,
    },
    "39": {
      "name": "avgNegGrade",
      "type": "sint16",
      "scale": 100,
      "offset": 0,
    },
    "40": {
      "name": "maxPosGrade",
      "type": "sint16",
      "scale": 100,
      "offset": 0,
    },
    "41": {
      "name": "maxNegGrade",
      "type": "sint16",
      "scale": 100,
      "offset": 0,
    },
    "42": {
      "name": "avgTemperature",
      "type": "sint8",
      "scale": 0,
      "offset": 0,
    },
    "43": {
      "name": "maxTemperature",
      "type": "sint8",
      "scale": 0,
      "offset": 0,
    },
    "44": {
      "name": "totalMovingTime",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "45": {
      "name": "avgPosVerticalSpeed",
      "type": "sint16",
      "scale": 1000,
      "offset": 0,
    },
    "46": {
      "name": "avgNegVerticalSpeed",
      "type": "sint16",
      "scale": 1000,
      "offset": 0,
    },
    "47": {
      "name": "maxPosVerticalSpeed",
      "type": "sint16",
      "scale": 1000,
      "offset": 0,
    },
    "48": {
      "name": "maxNegVerticalSpeed",
      "type": "sint16",
      "scale": 1000,
      "offset": 0,
    },
    "49": {
      "name": "timeInHrZone",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "50": {
      "name": "timeInSpeedZone",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "51": {
      "name": "timeInCadenceZone",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "52": {
      "name": "timeInPowerZone",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "53": {
      "name": "repetitionNum",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "54": {
      "name": "minAltitude",
      "type": "uint16",
      "scale": 5,
      "offset": 500,
    },
    "55": {
      "name": "minHeartRate",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "56": {
      "name": "activeTime",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "57": {
      "name": "wktStepIndex",
      "type": "messageIndex",
      "scale": 0,
      "offset": 0,
    },
    "58": {
      "name": "sportEvent",
      "type": "sportEvent",
      "scale": 0,
      "offset": 0,
    },
    "59": {
      "name": "avgLeftTorqueEffectiveness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "60": {
      "name": "avgRightTorqueEffectiveness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "61": {
      "name": "avgLeftPedalSmoothness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "62": {
      "name": "avgRightPedalSmoothness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "63": {
      "name": "avgCombinedPedalSmoothness",
      "type": "uint8",
      "scale": 2,
      "offset": 0,
    },
    "64": {
      "name": "status",
      "type": "segmentLapStatus",
      "scale": 0,
      "offset": 0,
    },
    "65": {
      "name": "uuid",
      "type": "string",
      "scale": 0,
      "offset": 0,
    },
    "66": {
      "name": "avgFractionalCadence",
      "type": "uint8",
      "scale": 128,
      "offset": 0,
    },
    "67": {
      "name": "maxFractionalCadence",
      "type": "uint8",
      "scale": 128,
      "offset": 0,
    },
    "68": {
      "name": "totalFractionalCycles",
      "type": "uint8",
      "scale": 128,
      "offset": 0,
    },
    "69": {
      "name": "frontGearShiftCount",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "70": {
      "name": "rearGearShiftCount",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "71": {
      "name": "timeStanding",
      "type": "uint32",
      "scale": 1000,
      "offset": 0,
    },
    "72": {
      "name": "standCount",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "73": {
      "name": "avgLeftPco",
      "type": "sint8",
      "scale": 0,
      "offset": 0,
    },
    "74": {
      "name": "avgRightPco",
      "type": "sint8",
      "scale": 0,
      "offset": 0,
    },
    "75": {
      "name": "avgLeftPowerPhase",
      "type": "uint8",
      "scale": 0.7111111,
      "offset": 0,
    },
    "76": {
      "name": "avgLeftPowerPhasePeak",
      "type": "uint8",
      "scale": 0.7111111,
      "offset": 0,
    },
    "77": {
      "name": "avgRightPowerPhase",
      "type": "uint8",
      "scale": 0.7111111,
      "offset": 0,
    },
    "78": {
      "name": "avgRightPowerPhasePeak",
      "type": "uint8",
      "scale": 0.7111111,
      "offset": 0,
    },
    "79": {
      "name": "avgPowerPosition",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "80": {
      "name": "maxPowerPosition",
      "type": "uint16",
      "scale": 0,
      "offset": 0,
    },
    "81": {
      "name": "avgCadencePosition",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
    "82": {
      "name": "maxCadencePosition",
      "type": "uint8",
      "scale": 0,
      "offset": 0,
    },
  },
  "147": {
    "0": {
      "name": "serialNumber",
      "type": "raw",
      "scale": 0,
      "offset": 0,
    },
    "2": {
      "name": "name",
      "type": "raw",
      "scale": 0,
      "offset": 0,
    },
    "17": {
      "name": "numFrontGears",
      "type": "raw",
      "scale": 0,
      "offset": 0,
    },
    "18": {
      "name": "frontGears",
      "type": "raw",
      "scale": 0,
      "offset": 0,
    },
    "19": {
      "name": "numBackGears",
      "type": "raw",
      "scale": 0,
      "offset": 0,
    },
    "20": {
      "name": "backGears",
      "type": "raw",
      "scale": 0,
      "offset": 0,
    },
    "32": {
      "name": "product",
      "type": "raw",
      "scale": 0,
      "offset": 0,
    },
    "34": {
      "name": "softwareVersion",
      "type": "raw",
      "scale": 0,
      "offset": 0,
    },
    "254": {
      "name": "messageIndex",
      "type": "messageIndex",
      "scale": 0,
      "offset": 0,
    },
  },
};
