name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: denolib/setup-deno@master
      with:
        deno-version: 1.8.1
    - name: Run linter
      run: |
        make lint
    - name: Run tests
      run: |
        make test
